### PR TITLE
Add HMR support

### PR DESCRIPTION
**Pull request by pstoica**
Hey, I had a similar realization that you could use RxJS to reimplement redux! I prototyped some of it here: https://github.com/pstoica/hot-reload-rxjs

It's a goofy repo, but the take-away was: use ReplaySubject for the dispatcher, and a flatMapLatest on the active reducer function will re-reduce over all the history ReplaySubject saved.

I also added the appropriate webpack config to counter-react-redux.

Let me know if I can help with anything else! I'm still pretty curious about using Rx as the backend for redux/time-travel ideas.

### CODE REVIEW

**Comment by pstoica** [comment]
Also, the buffer size should probably be configurable.

It is cool that you can configure ReplaySubject's buffer by time and/or element count. I could maybe imagine periodically serializing and storing user event data?

**Comment by jas-chen** [comment]
Hi @pstoica , thanks for the pr, but this makes HMR behavior not like the same as original redux, maybe user will be confused? What do you think?

**Comment by pstoica** [comment]
Hey! Turns out I've been totally misinterpreting what Redux was doing, sorry! At least the change is pretty small.

I think the examples did work the same as Redux with just the webpack changes.

**Comment by jas-chen** [comment]
Okay, I will update webpack config, thanks!

**Pull request closed without merging**
